[CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
empty=%ThemeDir%Nirvana Recycle Bin Empty.ico,0
full=%ThemeDir%Nirvana Recycle Bin Full.ico,0

[CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=%ThemeDir%Nirvana My Computer.ico,0

[CLSID\{208D2C60-3AEA-1069-A2D7-08002B30309D}\DefaultIcon]
DefaultValue=%ThemeDir%Nirvana Network Neighborhood.ico,0

[Control Panel\Cursors]
AppStarting=%ThemeDir%Nirvana Working In Background.cur
Arrow=%ThemeDir%Nirvana Normal.cur
Crosshair=%ThemeDir%Nirvana Precision.cur
Help=%ThemeDir%Nirvana Help.cur
IBeam=%ThemeDir%Nirvana Text.cur
No=%ThemeDir%Nirvana Unavailable.cur
NWPen=%ThemeDir%Nirvana Handwriting.cur
SizeAll=%ThemeDir%Nirvana Move.ani
SizeNESW=%ThemeDir%Nirvana Diagonal 2.ani
SizeNS=%ThemeDir%Nirvana Verticle.ani
SizeNWSE=%ThemeDir%Nirvana Diagonal 1.ani
SizeWE=%ThemeDir%Nirvana Horizontal.ani
UpArrow=%ThemeDir%Nirvana Alternate.cur
Wait=%ThemeDir%Nirvana Busy.cur

[Control Panel\Desktop]
Wallpaper=%ThemeDir%Nirvana Wallpaper.jpg
Pattern=(‚È‚µ)
TileWallpaper=0
WallpaperStyle=2

[AppEvents\Schemes\Apps\.Default\.Default\.Current]
DefaultValue=%ThemeDir%Nirvana Default.wav

[AppEvents\Schemes\Apps\.Default\Open\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\Close\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\MenuCommand\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\MenuPopup\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\InfraredInterrupted\.Current]
DefaultValue=%Windir%media\Houston.WAV

[AppEvents\Schemes\Apps\.Default\InfraredBeginCommunication\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\InfraredEndCommunication\.Current]
DefaultValue=%Windir%media\Hasta.WAV

[AppEvents\Schemes\Apps\.Default\InfraredBeginDeviceInRange\.Current]
DefaultValue=%Windir%media\Jaws.wav

[AppEvents\Schemes\Apps\.Default\InfraredEndDeviceInRange\.Current]
DefaultValue=%Windir%media\Alrighty.WAV

[AppEvents\Schemes\Apps\.Default\RingIn\.Current]
DefaultValue=%Windir%HELLO-C.WAV

[AppEvents\Schemes\Apps\.Default\Ringout\.Current]
DefaultValue=%Windir%HELLO.WAV

[AppEvents\Schemes\Apps\.Default\SystemDefault\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\SchdplusReminder\.Current]
DefaultValue=%ThemeDir%Crosshair

[AppEvents\Schemes\Apps\.Default\roachEnd\.Current]
DefaultValue=%ThemeDir%.Current

[AppEvents\Schemes\Apps\.Default\roachDone\.Current]
DefaultValue=%ThemeDir%No

[AppEvents\Schemes\Apps\.Default\roachStart\.Current]
DefaultValue=%ThemeDir%dariadefault.wav

[AppEvents\Schemes\Apps\Explorer\EmptyRecycleBin\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\SystemAsterisk\.Current]
DefaultValue=%ThemeDir%Nirvana Asterisk.wav

[AppEvents\Schemes\Apps\.Default\SystemHand\.Current]
DefaultValue=%ThemeDir%Nirvana Critical Stop.wav

[AppEvents\Schemes\Apps\.Default\EmptyRecycleBin\.Current]
DefaultValue=%ThemeDir%Nirvana Empty Recycle Bin.wav

[AppEvents\Schemes\Apps\.Default\SystemExclamation\.Current]
DefaultValue=%ThemeDir%Nirvana Exclamation.wav

[AppEvents\Schemes\Apps\.Default\SystemExit\.Current]
DefaultValue=%ThemeDir%Nirvana Exit Windows.wav

[AppEvents\Schemes\Apps\.Default\Maximize\.Current]
DefaultValue=%ThemeDir%Nirvana Maximize.wav

[AppEvents\Schemes\Apps\.Default\Minimize\.Current]
DefaultValue=%ThemeDir%Nirvana Minimize.wav

[AppEvents\Schemes\Apps\.Default\AppGPFault\.Current]
DefaultValue=%ThemeDir%Nirvana Program Error.wav

[AppEvents\Schemes\Apps\.Default\SystemQuestion\.Current]
DefaultValue=%ThemeDir%Nirvana Question.wav

[AppEvents\Schemes\Apps\.Default\RestoreDown\.Current]
DefaultValue=%ThemeDir%Nirvana Restore Down.wav

[AppEvents\Schemes\Apps\.Default\RestoreUp\.Current]
DefaultValue=%ThemeDir%Nirvana Restore Up.wav

[AppEvents\Schemes\Apps\.Default\SystemStart\.Current]
DefaultValue=%ThemeDir%Nirvana Start Windows.wav

[Metrics]
IconMetrics=76 0 0 0 77 0 0 0 82 0 0 0 1 0 0 0 248 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 0 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 224 249 251 191 0 0 0 0 164 72 66 0 96 22 104 0 113 30
NonclientMetrics=84 1 0 0 1 0 0 0 13 0 0 0 13 0 0 0 18 0 0 0 18 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 188 2 0 0 0 0 0 0 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 224 249 251 191 0 0 0 0 164 72 66 0 96 22 104 0 113 30 15 0 0 0 15 0 0 0 247 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 0 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 224 249 251 191 0 0 0 0 164 72 66 0 96 22 104 0 113 30 18 0 0 0 18 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 0 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 224 249 251 191 0 0 0 0 164 72 66 0 96 22 104 0 113 30 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 0 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 224 249 251 191 0 0 0 0 164 72 66 0 96 22 104 0 113 30 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 0 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 224 249 251 191 0 0 0 0 164 72 66 0 96 22 104 0 113 30

[Control Panel\Colors]
Scrollbar=200 224 216
Background=0 0 0
ActiveTitle=0 0 128
InactiveTitle=72 144 136
Menu=136 192 184
Window=200 224 216
WindowFrame=0 0 0
MenuText=0 0 0
WindowText=0 0 0
TitleText=192 192 192
ActiveBorder=136 192 184
InactiveBorder=136 192 184
AppWorkspace=75 141 132
Hilight=0 0 128
HilightText=255 255 255
ButtonFace=136 192 184
ButtonShadow=72 144 136
GrayText=72 144 136
ButtonText=0 0 0
InactiveTitleText=192 192 192
ButtonHilight=200 224 216
ButtonDkShadow=0 0 0
ButtonLight=136 192 184
InfoText=0 0 0
InfoWindow=200 224 216

[MasterThemeSelector]
MTSM=DABJDKT
ThemeColorBPP=8
ThemeImageBPP=8
Stretch=1
