export const langs = {
  "c": {
    name: "C",
    extensions: [".c", ".h", ".ino"],
    module: "cpp",
  },
  "c++": {
    name: "C++",
    alias: ["cpp"],
    extensions: [".cpp", ".c++", ".cc", ".cxx", ".hpp", ".h++", ".hh", ".hxx"],
    module: "cpp",
  },
  "cql": {
    name: "CQL",
    alias: ["cassandra"],
    extensions: [".cql"],
    module: "sql",
    options: {
      dialect: "Cassandra",
    },
  },
  "css": {
    name: "CSS",
    extensions: [".css"],
  },
  "go": {
    name: "Go",
    extensions: [".go"],
  },
  "html": {
    name: "HTML",
    alias: ["xhtml"],
    extensions: [".html", ".htm", ".handlebars", ".hbs"],
  },
  "java": {
    name: "Java",
    extensions: [".java"],
  },
  "javascript": {
    name: "JavaScript",
    alias: ["ecmascript", "js", "node"],
    extensions: [".js", ".mjs", ".cjs"],
  },
  "jinja": {
    name: "Jinja",
    extensions: [".j2", ".jinja", ".jinja2"],
  },
  "json": {
    name: "JSON",
    extensions: [".json", ".map"],
  },
  "json5": {
    name: "JSON5",
    extensions: [".json5"],
  },
  "jsx": {
    name: "JSX",
    extensions: [".jsx"],
    options: {
      jsx: true,
    },
    module: "javascript",
  },
  "less": {
    name: "LESS",
    extensions: [".less"],
  },
  "liquid": {
    name: "Liquid",
    extensions: [".liquid"],
  },
  "mariadb sql": {
    name: "MariaDB SQL",
    options: {
      dialect: "MariaSQL",
    },
    module: "sql",
  },
  "markdown": {
    name: "Markdown",
    extensions: [".md", ".markdown", ".mkd"],
  },
  "ms sql": {
    name: "MS SQL",
    module: "sql",
    options: {
      dialect: "MSSQL",
    },
  },
  "mysql": {
    name: "MySQL",
    module: "sql",
    options: {
      dialect: "MySQL",
    },
  },
  "php": {
    name: "PHP",
    extensions: [".php", ".php3", ".php4", ".php5", ".php7", ".phtml"],
  },
  "plsql": {
    name: "PLSQL",
    extensions: [".pls"],
    module: "sql",
    options: {
      dialect: "PLSQL",
    },
  },
  "postgresql": {
    name: "PostgreSQL",
    module: "sql",
    options: {
      dialect: "PostgreSQL",
    },
  },
  "python": {
    name: "Python",
    extensions: [".BUILD", ".bzl", ".py", ".pyw"],
    filename: /^(BUCK|BUILD)$/,
  },
  "rust": {
    name: "Rust",
    extensions: [".rs"],
  },
  "sass": {
    name: "Sass",
    extensions: [".sass"],
    options: {
      indented: true,
    },
  },
  "scss": {
    name: "SCSS",
    extensions: [".scss"],
    module: "sass",
  },
  "sql": {
    name: "SQL",
    extensions: [".sql"],
    options: {
      dialect: "StandardSQL",
    },
  },
  "sqlite": {
    name: "SQLite",
    module: "sql",
    options: {
      dialect: "SQLite",
    },
  },
  "tsx": {
    name: "TSX",
    extensions: [".tsx"],
    module: "javascript",
    options: {
      jsx: true,
      typescript: true,
    },
  },
  "typescript": {
    name: "TypeScript",
    alias: ["ts"],
    extensions: [".ts", ".mts", ".cts"],
    module: "javascript",
    options: {
      typescript: true,
    },
  },
  "webassembly": {
    name: "WebAssembly",
    extensions: [".wat", ".wast"],
    module: "wast",
  },
  "glsl": {
    name: "GLSL",
    extensions: [".glsl", ".vert", ".frag"],
  },
  "xml": {
    name: "XML",
    alias: ["rss", "wsdl", "xsd"],
    extensions: [".xml", ".xsl", ".xsd", ".svg"],
  },
  "yaml": {
    name: "YAML",
    alias: ["yml"],
    extensions: [".yaml", ".yml"],
  },
  "vue": {
    name: "Vue",
    extensions: [".vue"],
  },
  "angular template": {
    name: "Angular Template",
    module: "angular",
  },
  "apl": {
    name: "APL",
    extensions: [".dyalog", ".apl"],
    parser: true,
  },
  "pgp": {
    name: "PGP",
    alias: ["asciiarmor"],
    extensions: [".asc", ".pgp", ".sig"],
    module: "asciiarmor",
    export: "asciiArmor",
    parser: true,
  },
  "asn.1": {
    name: "ASN.1",
    extensions: [".asn", ".asn1"],
    module: "asn1",
    options: {},
    parser: true,
  },
  "asterisk": {
    name: "Asterisk",
    filename: /^extensions\.conf$/i,
    parser: true,
  },
  "brainfuck": {
    name: "Brainfuck",
    extensions: [".b", ".bf"],
    parser: true,
  },
  "cobol": {
    name: "Cobol",
    extensions: [".cob", ".cpy"],
    parser: true,
  },
  "c#": {
    name: "C#",
    alias: ["csharp", "cs"],
    extensions: [".cs"],
    module: "clike",
    export: "csharp",
    parser: true,
  },
  "clojure": {
    name: "Clojure",
    extensions: [".clj", ".cljc", ".cljx"],
    parser: true,
  },
  "clojurescript": {
    name: "ClojureScript",
    extensions: [".cljs"],
    module: "clojure",
    parser: true,
  },
  "closure stylesheets (gss)": {
    name: "Closure Stylesheets (GSS)",
    extensions: [".gss"],
    module: "css",
    export: "gss",
    parser: true,
  },
  "cmake": {
    name: "CMake",
    extensions: [".cmake", ".cmake.in"],
    filename: /^CMakeLists\.txt$/,
    parser: true,
  },
  "coffeescript": {
    name: "CoffeeScript",
    alias: ["coffee", "coffee-script"],
    extensions: [".coffee"],
    parser: true,
  },
  "common lisp": {
    name: "Common Lisp",
    alias: ["lisp"],
    extensions: [".cl", ".lisp", ".el"],
    module: "commonlisp",
    export: "commonLisp",
    parser: true,
  },
  "cypher": {
    name: "Cypher",
    extensions: [".cyp", ".cypher"],
    parser: true,
  },
  "cython": {
    name: "Cython",
    extensions: [".pyx", ".pxd", ".pxi"],
    export: "cython",
    parser: true,
  },
  "crystal": {
    name: "Crystal",
    extensions: [".cr"],
    parser: true,
  },
  "d": {
    name: "D",
    extensions: [".d"],
    parser: true,
  },
  "dart": {
    name: "Dart",
    extensions: [".dart"],
    module: "clike",
    export: "dart",
    parser: true,
  },
  "diff": {
    name: "diff",
    extensions: [".diff", ".patch"],
    parser: true,
  },
  "dockerfile": {
    name: "Dockerfile",
    filename: /^Dockerfile$/,
    parser: true,
  },
  "dtd": {
    name: "DTD",
    extensions: [".dtd"],
    parser: true,
  },
  "dylan": {
    name: "Dylan",
    extensions: [".dylan", ".dyl", ".intr"],
    parser: true,
  },
  "ebnf": {
    name: "EBNF",
    parser: true,
  },
  "ecl": {
    name: "ECL",
    extensions: [".ecl"],
    parser: true,
  },
  "edn": {
    name: "edn",
    extensions: [".edn"],
    module: "clojure",
    parser: true,
  },
  "eiffel": {
    name: "Eiffel",
    extensions: [".e"],
    parser: true,
  },
  "elm": {
    name: "Elm",
    extensions: [".elm"],
    parser: true,
  },
  "erlang": {
    name: "Erlang",
    extensions: [".erl"],
    parser: true,
  },
  "esper": {
    name: "Esper",
    export: "esper",
    parser: true,
  },
  "factor": {
    name: "Factor",
    extensions: [".factor"],
    parser: true,
  },
  "fcl": {
    name: "FCL",
    parser: true,
  },
  "forth": {
    name: "Forth",
    extensions: [".forth", ".fth", ".4th"],
    parser: true,
  },
  "fortran": {
    name: "Fortran",
    extensions: [".f", ".for", ".f77", ".f90", ".f95"],
    parser: true,
  },
  "f#": {
    name: "F#",
    alias: ["fsharp"],
    extensions: [".fs"],
    module: "mllike",
    export: "fSharp",
    parser: true,
  },
  "gas": {
    name: "Gas",
    extensions: [".s"],
    parser: true,
  },
  "gherkin": {
    name: "Gherkin",
    extensions: [".feature"],
    parser: true,
  },
  "groovy": {
    name: "Groovy",
    extensions: [".groovy", ".gradle"],
    filename: /^Jenkinsfile$/,
    parser: true,
  },
  "haskell": {
    name: "Haskell",
    extensions: [".hs"],
    parser: true,
  },
  "haxe": {
    name: "Haxe",
    extensions: [".hx"],
    parser: true,
  },
  "hxml": {
    name: "HXML",
    extensions: [".hxml"],
    module: "haxe",
    export: "hxml",
    parser: true,
  },
  "http": {
    name: "HTTP",
    parser: true,
  },
  "idl": {
    name: "IDL",
    extensions: [".pro"],
    parser: true,
  },
  "json-ld": {
    name: "JSON-LD",
    alias: ["jsonld"],
    extensions: [".jsonld"],
    export: "jsonld",
    parser: true,
  },
  "julia": {
    name: "Julia",
    extensions: [".jl"],
    parser: true,
  },
  "kotlin": {
    name: "Kotlin",
    extensions: [".kt", ".kts"],
    module: "clike",
    export: "kotlin",
    parser: true,
  },
  "livescript": {
    name: "LiveScript",
    alias: ["ls"],
    extensions: [".ls"],
    export: "liveScript",
    parser: true,
  },
  "lua": {
    name: "Lua",
    extensions: [".lua"],
    parser: true,
  },
  "mirc": {
    name: "mIRC",
    extensions: [".mrc"],
    parser: true,
  },
  "mathematica": {
    name: "Mathematica",
    extensions: [".m", ".nb", ".wl", ".wls"],
    parser: true,
  },
  "modelica": {
    name: "Modelica",
    extensions: [".mo"],
    parser: true,
  },
  "mumps": {
    name: "MUMPS",
    extensions: [".mps"],
    parser: true,
  },
  "mbox": {
    name: "Mbox",
    extensions: [".mbox"],
    parser: true,
  },
  "nginx": {
    name: "Nginx",
    filename: /nginx.*\.conf$/i,
    parser: true,
  },
  "nsis": {
    name: "NSIS",
    extensions: [".nsh", ".nsi"],
    parser: true,
  },
  "ntriples": {
    name: "NTriples",
    extensions: [".nt", ".nq"],
    parser: true,
  },
  "objective-c": {
    name: "Objective-C",
    alias: ["objective-c", "objc"],
    extensions: [".m"],
    module: "clike",
    export: "objectiveC",
    parser: true,
  },
  "objective-c++": {
    name: "Objective-C++",
    alias: ["objective-c++", "objc++"],
    extensions: [".mm"],
    module: "clike",
    export: "objectiveCpp",
    parser: true,
  },
  "ocaml": {
    name: "OCaml",
    extensions: [".ml", ".mli", ".mll", ".mly"],
    module: "mllike",
    export: "oCaml",
    parser: true,
  },
  "octave": {
    name: "Octave",
    extensions: [".m"],
    parser: true,
  },
  "oz": {
    name: "Oz",
    extensions: [".oz"],
    parser: true,
  },
  "pascal": {
    name: "Pascal",
    extensions: [".p", ".pas"],
    parser: true,
  },
  "perl": {
    name: "Perl",
    extensions: [".pl", ".pm"],
    parser: true,
  },
  "pig": {
    name: "Pig",
    extensions: [".pig"],
    parser: true,
  },
  "powershell": {
    name: "PowerShell",
    extensions: [".ps1", ".psd1", ".psm1"],
    export: "powerShell",
    parser: true,
  },
  "properties": {
    name: "Properties",
    alias: ["ini", "properties"],
    extensions: [".properties", ".ini", ".in", ".desktop", ".url"],
    filename: /^.directory$/,
    module: "properties",
    parser: true,
  },
  "protobuf": {
    name: "ProtoBuf",
    extensions: [".proto"],
    parser: true,
  },
  "pug": {
    name: "Pug",
    alias: ["jade"],
    extensions: [".pug", ".jade"],
    parser: true,
  },
  "puppet": {
    name: "Puppet",
    extensions: [".pp"],
    parser: true,
  },
  "q": {
    name: "Q",
    extensions: [".q"],
    parser: true,
  },
  "r": {
    name: "R",
    alias: ["rscript"],
    extensions: [".r", ".R"],
    parser: true,
  },
  "rpm changes": {
    name: "RPM Changes",
    module: "rpm",
    export: "rpmChanges",
    parser: true,
  },
  "rpm spec": {
    name: "RPM Spec",
    extensions: [".spec"],
    module: "rpm",
    export: "rpmSpec",
    parser: true,
  },
  "ruby": {
    name: "Ruby",
    alias: ["jruby", "macruby", "rake", "rb", "rbx"],
    extensions: [".rb"],
    filename: /^(Gemfile|Rakefile)$/,
    parser: true,
  },
  "sas": {
    name: "SAS",
    extensions: [".sas"],
    parser: true,
  },
  "scala": {
    name: "Scala",
    extensions: [".scala"],
    module: "clike",
    export: "scala",
    parser: true,
  },
  "scheme": {
    name: "Scheme",
    extensions: [".scm", ".ss"],
    parser: true,
  },
  "shell": {
    name: "Shell",
    alias: ["bash", "sh", "zsh"],
    extensions: [".sh", ".ksh", ".bash"],
    filename: /^PKGBUILD$/,
    parser: true,
  },
  "sieve": {
    name: "Sieve",
    extensions: [".siv", ".sieve"],
    parser: true,
  },
  "smalltalk": {
    name: "Smalltalk",
    extensions: [".st"],
    parser: true,
  },
  "solr": {
    name: "Solr",
    parser: true,
  },
  "sml": {
    name: "SML",
    extensions: [".sml", ".sig", ".fun", ".smackspec"],
    module: "mllike",
    export: "sml",
    parser: true,
  },
  "sparql": {
    name: "SPARQL",
    alias: ["sparul"],
    extensions: [".rq", ".sparql"],
    parser: true,
  },
  "spreadsheet": {
    name: "Spreadsheet",
    alias: ["excel", "formula"],
    parser: true,
  },
  "squirrel": {
    name: "Squirrel",
    extensions: [".nut"],
    module: "clike",
    export: "squirrel",
    parser: true,
  },
  "stylus": {
    name: "Stylus",
    extensions: [".styl"],
    parser: true,
  },
  "swift": {
    name: "Swift",
    extensions: [".swift"],
    parser: true,
  },
  "stex": {
    name: "sTeX",
    parser: true,
  },
  "latex": {
    name: "LaTeX",
    alias: ["tex"],
    extensions: [".text", ".ltx", ".tex"],
    module: "stex",
    parser: true,
  },
  "systemverilog": {
    name: "SystemVerilog",
    extensions: [".v", ".sv", ".svh"],
    module: "verilog",
    parser: true,
  },
  "tcl": {
    name: "Tcl",
    extensions: [".tcl"],
    parser: true,
  },
  "textile": {
    name: "Textile",
    extensions: [".textile"],
    parser: true,
  },
  "tiddlywiki": {
    name: "TiddlyWiki",
    export: "tiddlyWiki",
    parser: true,
  },
  "tiki wiki": {
    name: "Tiki wiki",
    module: "tiki",
    parser: true,
  },
  "toml": {
    name: "TOML",
    extensions: [".toml"],
    parser: true,
  },
  "troff": {
    name: "Troff",
    extensions: [".1", ".2", ".3", ".4", ".5", ".6", ".7", ".8", ".9"],
    parser: true,
  },
  "ttcn": {
    name: "TTCN",
    extensions: [".ttcn", ".ttcn3", ".ttcnpp"],
    parser: true,
  },
  "ttcn_cfg": {
    name: "TTCN_CFG",
    extensions: [".cfg"],
    module: "ttcn",
    export: "ttcnCfg",
    parser: true,
  },
  "turtle": {
    name: "Turtle",
    extensions: [".ttl"],
    parser: true,
  },
  "web idl": {
    name: "Web IDL",
    extensions: [".webidl"],
    module: "webidl",
    export: "webIDL",
    parser: true,
  },
  "vb.net": {
    name: "VB.NET",
    extensions: [".vb"],
    module: "vb",
    parser: true,
  },
  "vbscript": {
    name: "VBScript",
    extensions: [".vbs"],
    export: "vbScript",
    parser: true,
  },
  "velocity": {
    name: "Velocity",
    extensions: [".vtl"],
    parser: true,
  },
  "verilog": {
    name: "Verilog",
    extensions: [".v"],
    parser: true,
  },
  "vhdl": {
    name: "VHDL",
    extensions: [".vhd", ".vhdl"],
    parser: true,
  },
  "xquery": {
    name: "XQuery",
    extensions: [".xy", ".xquery", ".xq", ".xqm", ".xqy"],
    export: "xQuery",
    parser: true,
  },
  "yacas": {
    name: "Yacas",
    extensions: [".ys"],
    parser: true,
  },
  "z80": {
    name: "Z80",
    extensions: [".z80"],
    parser: true,
  },
  "mscgen": {
    name: "MscGen",
    extensions: [".mscgen", ".mscin", ".msc"],
    parser: true,
  },
  "xù": {
    name: "Xù",
    extensions: [".xu"],
    module: "mscgen",
    export: "xu",
    parser: true,
  },
  "msgenny": {
    name: "MsGenny",
    extensions: [".msgenny"],
    module: "mscgen",
    export: "msgenny",
    parser: true,
  },
}
