// Author: William D. Neumann
export default {
  variant: "dark",
  settings: {
    background: "#200020",
    foreground: "#D0D0FF",
    caret: "#7070FF",
    selection: "#80000080",
    gutterBackground: "#200020",
    gutterForeground: "#C080C0",
    lineHighlight: "#80000040",
  },
  styles: [
    { tag: "comment", color: "#404080" },
    { tag: ["string", "regexp"], color: "#999999" },
    { tag: "number", color: "#7090B0" },
    { tag: ["bool", "null"], color: "#8080A0" },
    { tag: ["punctuation", "derefOperator"], color: "#805080" },
    { tag: "keyword", color: "#60B0FF" },
    { tag: "definitionKeyword", color: "#B0FFF0" },
    { tag: "moduleKeyword", color: "#60B0FF" },
    { tag: "operator", color: "#A0A0FF" },
    { tag: ["variableName", "self"], color: "#008080" },
    { tag: "operatorKeyword", color: "#A0A0FF" },
    { tag: "controlKeyword", color: "#80A0FF" },
    { tag: "className", color: "#70E080" },
    { tag: ["function.propertyName", "propertyName"], color: "#50A0A0" },
    { tag: "tagName", color: "#009090" },
    { tag: "modifier", color: "#B0FFF0" },
    { tag: ["squareBracket", "attributeName"], color: "#D0D0FF" },
  ],
}
