const c = {
  background: "#23262E",
  foreground: "#D5CED9",
  selection: "#db45a280",
  selectionMatch: "#db45a280",
  cursor: "var(--cursor-#FFF)",
  dropdownBackground: "#2b303b",
  dropdownBorder: "#363c49",
  activeLine: "#596a992e",
  matchingBracket: "#746f77",
  keyword: "#c74ded",
  storage: "#c74ded",
  variable: "#00e8c6",
  parameter: "#00e8c6",
  function: "#FFE66D",
  string: "#96E072",
  constant: "#ee5d43",
  type: "#FFE66D",
  class: "#FFE66D",
  number: "#ee5d43",
  comment: "#A0A1A7cc",
  heading: "#ff00aa",
  invalid: null,
  regexp: "#96E072",
  tag: "#f92672",
}

export default {
  variant: "dark",
  settings: {
    background: c.background,
    foreground: c.foreground,
    caret: c.cursor,
    selection: c.selection,
    selectionMatch: c.selectionMatch,
    gutterBackground: c.background,
    gutterForeground: c.foreground,
    lineHighlight: c.activeLine,
  },
  styles: [
    { tag: "keyword", color: c.keyword },
    { tag: ["name", "deleted", "character", "macroName"], color: c.variable },
    { tag: ["propertyName"], color: c.function },
    {
      tag: ["processingInstruction", "string", "inserted", "special.string"],
      color: c.string,
    },
    { tag: ["function.variableName", "labelName"], color: c.function },
    { tag: ["color", "constant.name", "standard.name"], color: c.constant },
    { tag: ["definition.name", "separator"], color: c.variable },
    { tag: ["className"], color: c.class },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: c.number,
    },
    { tag: ["typeName"], color: c.type, fontStyle: c.type },
    { tag: ["operator"], color: c.keyword },
    { tag: ["url", "escape", "regexp", "link"], color: c.regexp },
    { tag: ["meta", "comment"], color: c.comment },
    { tag: "tagName", color: c.tag },
    { tag: "strong", fontWeight: "bold" },
    { tag: "emphasis", fontStyle: "italic" },
    { tag: "link", textDecoration: "underline" },
    { tag: "heading", fontWeight: "bold", color: c.heading },
    { tag: ["atom", "special.variableName"], color: c.variable },
    { tag: "invalid", color: c.invalid },
    { tag: "strikethrough", textDecoration: "line-through" },
    {
      tag: ["operatorKeyword", "bool", "null", "variableName"],
      color: c.constant,
    },
  ],
}
