export default {
  variant: "dark",
  settings: {
    background: "#21202e",
    foreground: "#edecee",
    caret: "#a277ff",
    selection: "#5a51898f",
    selectionMatch: "#5a51898f",
    gutterBackground: "#21202e",
    gutterForeground: "#edecee",
    gutterBorder: "transparent",
    lineHighlight: "#a394f033",
  },
  styles: [
    { tag: "keyword", color: "#a277ff" },
    { tag: ["name", "deleted", "character", "macroName"], color: "#edecee" },
    { tag: ["propertyName"], color: "#ffca85" },
    {
      tag: ["processingInstruction", "string", "inserted", "special.string"],
      color: "#61ffca",
    },
    { tag: ["function.variableName", "labelName"], color: "#ffca85" },
    { tag: ["color", "constant.name", "standard.name"], color: "#61ffca" },
    { tag: ["definition.name", "separator"], color: "#edecee" },
    { tag: ["className"], color: "#82e2ff" },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: "#61ffca",
    },
    { tag: ["typeName"], color: "#82e2ff" },
    { tag: ["operator", "operatorKeyword"], color: "#a277ff" },
    { tag: ["url", "escape", "regexp", "link"], color: "#61ffca" },
    { tag: ["meta", "comment"], color: "#6d6d6d" },
    { tag: "strong", fontWeight: "bold" },
    { tag: "emphasis", fontStyle: "italic" },
    { tag: "link", textDecoration: "underline" },
    { tag: "heading", fontWeight: "bold", color: "#a277ff" },
    { tag: ["atom", "bool", "special.variableName"], color: "#edecee" },
    { tag: "invalid", color: "#ff6767" },
    { tag: "strikethrough", textDecoration: "line-through" },
  ],
}
