export default {
  variant: "light",
  settings: {
    background: "#ffffff",
    foreground: "#2e3440",
    caret: "#3b4252",
    selection: "#eceff4",
    selectionMatch: "#e5e9f0",
    gutterBackground: "#eceff4",
    gutterForeground: "#2e3440",
    gutterBorder: "none",
    lineHighlight: "#02255f11",
  },
  styles: [
    { tag: "keyword", color: "#5e81ac" },
    {
      tag: ["name", "deleted", "character", "propertyName", "macroName"],
      color: "#d08770",
    },
    { tag: ["variableName"], color: "#d08770" },
    { tag: ["function.variableName"], color: "#5e81ac" },
    { tag: ["labelName"], color: "#81a1c1" },
    { tag: ["color", "constant.name", "standard.name"], color: "#5e81ac" },
    { tag: ["definition.name", "separator"], color: "#a3be8c" },
    { tag: ["brace"], color: "#8fbcbb" },
    { tag: ["annotation"], color: "#d30102" },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: "#88c0d0",
    },
    { tag: ["typeName", "className"], color: "#ebcb8b" },
    { tag: ["operator", "operatorKeyword"], color: "#a3be8c" },
    { tag: ["tagName"], color: "#b48ead" },
    { tag: ["squareBracket"], color: "#bf616a" },
    { tag: ["angleBracket"], color: "#d08770" },
    { tag: ["attributeName"], color: "#ebcb8b" },
    { tag: ["regexp"], color: "#5e81ac" },
    { tag: ["quote"], color: "#3b4252" },
    { tag: ["string"], color: "#d08770" },
    {
      tag: "link",
      color: "#8fbcbb",
      textDecoration: "underline",
      textUnderlinePosition: "under",
    },
    { tag: ["url", "escape", "special.string"], color: "#d08770" },
    { tag: ["meta"], color: "#88c0d0" },
    { tag: ["comment"], color: "#434c5e", fontStyle: "italic" },
    { tag: "strong", fontWeight: "bold", color: "#5e81ac" },
    { tag: "emphasis", fontStyle: "italic", color: "#5e81ac" },
    { tag: "strikethrough", textDecoration: "line-through" },
    { tag: "heading", fontWeight: "bold", color: "#5e81ac" },
    { tag: "special.heading1", fontWeight: "bold", color: "#5e81ac" },
    { tag: "heading1", fontWeight: "bold", color: "#5e81ac" },
    {
      tag: ["heading2", "heading3", "heading4"],
      fontWeight: "bold",
      color: "#5e81ac",
    },
    {
      tag: ["heading5", "heading6"],
      color: "#5e81ac",
    },
    { tag: ["atom", "bool", "special.variableName"], color: "#d08770" },
    {
      tag: ["processingInstruction", "inserted"],
      color: "#8fbcbb",
    },
    { tag: ["contentSeparator"], color: "#ebcb8b" },
    { tag: "invalid", color: "#434c5e", borderBottom: "1px dotted #d30102" },
  ],
}
