export default {
  variant: "dark",
  settings: {
    background: "#2E3235",
    foreground: "#DDDDDD",
    caret: "#DDDDDD",
    selection: "#202325",
    selectionMatch: "#202325",
    gutterBackground: "#292d30",
    gutterForeground: "#808080",
    gutterBorder: "1px solid #ffffff10",
    lineHighlight: "#B9D2FF30",
  },
  styles: [
    { tag: "keyword", color: "#fda331" },
    {
      tag: ["name", "deleted", "character", "propertyName", "macroName"],
      color: "#b5bd68",
    },
    { tag: ["variableName"], color: "#6fb3d2" },
    { tag: ["function.variableName"], color: "#fda331" },
    { tag: ["labelName"], color: "#fc6d24" },
    { tag: ["color", "constant.name", "standard.name"], color: "#fda331" },
    { tag: ["definition.name", "separator"], color: "#cc99cc" },
    { tag: ["brace"], color: "#cc99cc" },
    { tag: ["annotation"], color: "#fc6d24" },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: "#fda331",
    },
    { tag: ["typeName", "className"], color: "#6fb3d2" },
    { tag: ["operator", "operatorKeyword"], color: "#cc99cc" },
    { tag: ["tagName"], color: "#fda331" },
    { tag: ["squareBracket"], color: "#cc99cc" },
    { tag: ["angleBracket"], color: "#cc99cc" },
    { tag: ["attributeName"], color: "#6fb3d2" },
    { tag: ["regexp"], color: "#fda331" },
    { tag: ["quote"], color: "#DDDDDD" },
    { tag: ["string"], color: "#b5bd68" },
    {
      tag: "link",
      color: "#6987AF",
      textDecoration: "underline",
      textUnderlinePosition: "under",
    },
    { tag: ["url", "escape", "special.string"], color: "#8abeb7" },
    { tag: ["meta"], color: "#A54543" },
    { tag: ["comment"], color: "#808080", fontStyle: "italic" },
    { tag: "monospace", color: "#DDDDDD" },
    { tag: "strong", fontWeight: "bold", color: "#fda331" },
    { tag: "emphasis", fontStyle: "italic", color: "#6fb3d2" },
    { tag: "strikethrough", textDecoration: "line-through" },
    { tag: "heading", fontWeight: "bold", color: "#DDDDDD" },
    { tag: "special.heading1", fontWeight: "bold", color: "#DDDDDD" },
    { tag: "heading1", fontWeight: "bold", color: "#DDDDDD" },
    {
      tag: ["heading2", "heading3", "heading4"],
      fontWeight: "bold",
      color: "#DDDDDD",
    },
    { tag: ["heading5", "heading6"], color: "#DDDDDD" },
    { tag: ["atom", "bool", "special.variableName"], color: "#8abeb7" },
    { tag: ["processingInstruction", "inserted"], color: "#8abeb7" },
    { tag: ["contentSeparator"], color: "#6fb3d2" },
    {
      tag: "invalid",
      color: "#B9D2FF",
      borderBottom: `1px dotted ${"#fc6d24"}`,
    },
  ],
}
