export default {
  variant: "light",
  settings: {
    background: "#FFFFFF",
    foreground: "#000000",
    caret: "#FBAC52",
    selection: "#FFD420",
    selectionMatch: "#FFD420",
    gutterBackground: "#f5f5f5",
    gutterForeground: "#4D4D4C",
    gutterBorder: "transparent",
    lineHighlight: "#00000012",
  },
  styles: [
    { tag: ["meta", "comment"], color: "#804000" },
    { tag: ["keyword", "strong"], color: "#0000FF" },
    { tag: ["number"], color: "#FF0080" },
    { tag: ["string"], color: "#FF0080" },
    { tag: ["variableName"], color: "#006600" },
    { tag: ["escape"], color: "#33CC33" },
    { tag: ["tagName"], color: "#1C02FF" },
    { tag: ["heading"], color: "#0C07FF" },
    { tag: ["quote"], color: "#000000" },
    { tag: ["list"], color: "#B90690" },
    { tag: ["documentMeta"], color: "#888888" },
    { tag: ["function.variableName"], color: "#0000A2" },
    { tag: ["definition.typeName", "typeName"], color: "#6D79DE" },
  ],
}
