const c = {
  background: "#232a2f",
  foreground: "#939da5",
  selection: "#204062",
  selectionMatch: "#204062",
  cursor: "var(--cursor-#939da5)",
  dropdownBackground: "#1a2023",
  activeLine: "#4469832b",
  matchingBracket: "#204062",
  keyword: "#ba8ef7",
  storage: "#ba8ef7",
  variable: "#939da5",
  parameter: "#939da5",
  function: "#ffea6b",
  string: "#5bec95",
  constant: "#939da5",
  type: "#89ddff",
  class: "#ffea6b",
  number: "#89ddff",
  comment: "#707a84",
  heading: "#5bec95",
  invalid: "#ff6a80",
  regexp: "#56adb7",
  tag: "#ff6a80",
}

export default {
  variant: "dark",
  settings: {
    background: c.background,
    foreground: c.foreground,
    caret: c.cursor,
    selection: c.selection,
    selectionMatch: c.selectionMatch,
    gutterBackground: c.background,
    gutterForeground: c.foreground,
    lineHighlight: c.activeLine,
  },
  styles: [
    { tag: "keyword", color: c.keyword },
    { tag: ["name", "deleted", "character", "macroName"], color: c.variable },
    { tag: ["propertyName"], color: c.function },
    {
      tag: ["processingInstruction", "string", "inserted", "special.string"],
      color: c.string,
    },
    { tag: ["function.variableName", "labelName"], color: c.function },
    { tag: ["color", "constant.name", "standard.name"], color: c.constant },
    { tag: ["definition.name", "separator"], color: c.variable },
    { tag: ["className"], color: c.class },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: c.number,
    },
    { tag: ["typeName"], color: c.type, fontStyle: c.type },
    { tag: ["operator"], color: c.keyword },
    { tag: ["url", "escape", "regexp", "link"], color: c.regexp },
    { tag: ["meta", "comment"], color: c.comment },
    { tag: "tagName", color: c.tag },
    { tag: "strong", fontWeight: "bold" },
    { tag: "emphasis", fontStyle: "italic" },
    { tag: "link", textDecoration: "underline" },
    { tag: "heading", fontWeight: "bold", color: c.heading },
    { tag: ["atom", "special.variableName"], color: c.variable },
    { tag: "invalid", color: c.invalid },
    { tag: "strikethrough", textDecoration: "line-through" },
    {
      tag: ["operatorKeyword", "bool", "null", "variableName"],
      color: c.constant,
    },
  ],
}
