export default {
  variant: "light",
  settings: {
    background: "#fff",
    foreground: "#000",
    caret: "#FFFFFF",
    selection: "#d7d4f0",
    selectionMatch: "#d7d4f0",
    gutterBackground: "#f7f7f7",
    gutterForeground: "#999",
    lineHighlight: "#006fff1c",
    gutterBorder: "transparent",
  },
  styles: [
    { tag: ["comment"], color: "#3F7F5F" },
    { tag: ["documentMeta"], color: "#FF1717" },
    { tag: "keyword", color: "#7F0055", fontWeight: "bold" },
    { tag: "atom", color: "#00f" },
    { tag: "number", color: "#164" },
    { tag: "propertyName", color: "#164" },
    { tag: ["variableName", "definition.variableName"], color: "#0000C0" },
    { tag: "function.variableName", color: "#0000C0" },
    { tag: "string", color: "#2A00FF" },
    { tag: "operator", color: "black" },
    { tag: "tagName", color: "#170" },
    { tag: "attributeName", color: "#00c" },
    { tag: "link", color: "#219" },
  ],
}
