const c = {
  background: "#221a0f",
  foreground: "#d3af86",
  selection: "#84613daa",
  selectionMatch: "#84613daa",
  cursor: "var(--cursor-#d3af86)",
  dropdownBackground: "#51412c",
  activeLine: "#5e452b52",
  matchingBracket: "#5e452b",
  keyword: "#98676a",
  storage: "#98676a",
  variable: "#dc3958",
  parameter: "#dc3958",
  function: "#7e602c",
  string: "#889b4a",
  constant: "#f79a32",
  type: "#f06431",
  class: "#f06431",
  number: "#f79a32",
  comment: "#a57a4c",
  heading: "#8ab1b0",
  invalid: "#dc3958",
  regexp: "#7e602c",
  tag: "#dc3958",
}

export default {
  variant: "dark",
  settings: {
    background: c.background,
    foreground: c.foreground,
    caret: c.cursor,
    selection: c.selection,
    selectionMatch: c.selection,
    gutterBackground: c.background,
    gutterForeground: c.foreground,
    lineHighlight: c.activeLine,
  },
  styles: [
    { tag: "keyword", color: c.keyword },
    { tag: ["name", "deleted", "character", "macroName"], color: c.variable },
    { tag: ["propertyName"], color: c.function },
    {
      tag: ["processingInstruction", "string", "inserted", "special.string"],
      color: c.string,
    },
    { tag: ["function.variableName", "labelName"], color: c.function },
    { tag: ["color", "constant.name", "standard.name"], color: c.constant },
    { tag: ["definition.name", "separator"], color: c.variable },
    { tag: ["className"], color: c.class },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: c.number,
    },
    { tag: ["typeName"], color: c.type, fontStyle: c.type },
    { tag: ["operator", "operatorKeyword"], color: c.keyword },
    { tag: ["url", "escape", "regexp", "link"], color: c.regexp },
    { tag: ["meta", "comment"], color: c.comment },
    { tag: "tagName", color: c.tag },
    { tag: "strong", fontWeight: "bold" },
    { tag: "emphasis", fontStyle: "italic" },
    { tag: "link", textDecoration: "underline" },
    { tag: "heading", fontWeight: "bold", color: c.heading },
    { tag: ["atom", "bool", "special.variableName"], color: c.variable },
    { tag: "invalid", color: c.invalid },
    { tag: "strikethrough", textDecoration: "line-through" },
  ],
}
