export default {
  variant: "light",
  settings: {
    background: "#FAFAFA",
    foreground: "#90A4AE",
    caret: "#272727",
    selection: "#80CBC440",
    selectionMatch: "#80CBC440",
    gutterBackground: "#FAFAFA",
    gutterForeground: "#90A4AE",
    gutterBorder: "transparent",
    lineHighlight: "#CCD7DA50",
  },
  styles: [
    { tag: "keyword", color: "#39ADB5" },
    { tag: ["name", "deleted", "character", "macroName"], color: "#90A4AE" },
    { tag: ["propertyName"], color: "#6182B8" },
    {
      tag: ["processingInstruction", "string", "inserted", "special.string"],
      color: "#91B859",
    },
    { tag: ["function.variableName", "labelName"], color: "#6182B8" },
    { tag: ["color", "constant.name", "standard.name"], color: "#39ADB5" },
    { tag: ["definition.name", "separator"], color: "#90A4AE" },
    { tag: ["className"], color: "#E2931D" },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: "#F76D47",
    },
    { tag: ["typeName"], color: "#E2931D", fontStyle: "#E2931D" },
    { tag: ["operator", "operatorKeyword"], color: "#39ADB5" },
    { tag: ["url", "escape", "regexp", "link"], color: "#91B859" },
    { tag: ["meta", "comment"], color: "#90A4AE" },
    { tag: "strong", fontWeight: "bold" },
    { tag: "emphasis", fontStyle: "italic" },
    { tag: "link", textDecoration: "underline" },
    { tag: "heading", fontWeight: "bold", color: "#39ADB5" },
    { tag: ["atom", "bool", "special.variableName"], color: "#90A4AE" },
    { tag: "invalid", color: "#E5393570" },
    { tag: "strikethrough", textDecoration: "line-through" },
  ],
}
