export default {
  variant: "dark",
  settings: {
    background: "#2e3235",
    foreground: "#bdbdbd",
    caret: "#a0a4ae",
    selection: "#d7d4f063",
    selectionMatch: "#d7d4f063",
    gutterBackground: "#2e3235",
    gutterForeground: "#999",
    gutterActiveForeground: "#4f5b66",
    lineHighlight: "#545b6130",
  },
  styles: [
    { tag: "keyword", color: "#cf6edf" },
    { tag: ["name", "deleted", "character", "macroName"], color: "#56c8d8" },
    { tag: ["propertyName"], color: "#facf4e" },
    { tag: ["variableName"], color: "#bdbdbd" },
    { tag: ["function.variableName"], color: "#56c8d8" },
    { tag: ["labelName"], color: "#cf6edf" },
    { tag: ["color", "constant.name", "standard.name"], color: "#facf4e" },
    { tag: ["definition.name", "separator"], color: "#fa5788" },
    { tag: ["brace"], color: "#cf6edf" },
    { tag: ["annotation"], color: "#ff5f52" },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: "#ffad42",
    },
    { tag: ["typeName", "className"], color: "#ffad42" },
    { tag: ["operator", "operatorKeyword"], color: "#7186f0" },
    { tag: ["tagName"], color: "#99d066" },
    { tag: ["squareBracket"], color: "#ff5f52" },
    { tag: ["angleBracket"], color: "#606f7a" },
    { tag: ["attributeName"], color: "#bdbdbd" },
    { tag: ["regexp"], color: "#ff5f52" },
    { tag: ["quote"], color: "#6abf69" },
    { tag: ["string"], color: "#99d066" },
    {
      tag: "link",
      color: "#56c8d8",
      textDecoration: "underline",
      textUnderlinePosition: "under",
    },
    { tag: ["url", "escape", "special.string"], color: "#facf4e" },
    { tag: ["meta"], color: "#707d8b" },
    { tag: ["comment"], color: "#707d8b", fontStyle: "italic" },
    { tag: "monospace", color: "#bdbdbd" },
    { tag: "strong", fontWeight: "bold", color: "#ff5f52" },
    { tag: "emphasis", fontStyle: "italic", color: "#99d066" },
    { tag: "strikethrough", textDecoration: "line-through" },
    { tag: "heading", fontWeight: "bold", color: "#facf4e" },
    { tag: "heading1", fontWeight: "bold", color: "#facf4e" },
    {
      tag: ["heading2", "heading3", "heading4"],
      fontWeight: "bold",
      color: "#facf4e",
    },
    { tag: ["heading5", "heading6"], color: "#facf4e" },
    { tag: ["atom", "bool", "special.variableName"], color: "#56c8d8" },
    { tag: ["processingInstruction", "inserted"], color: "#ff5f52" },
    { tag: ["contentSeparator"], color: "#56c8d8" },
    { tag: "invalid", color: "#606f7a", borderBottom: `1px dotted #ff5f52` },
  ],
}
