const c = {
  background: "#272822",
  foreground: "#f8f8f2",
  selection: "#4a4a76",
  selectionMatch: "#4a4a76",
  cursor: "var(--cursor-#f8f8f0)",
  dropdownBackground: "#414339",
  activeLine: "#3e3d3257",
  matchingBracket: "#3e3d32",
  keyword: "#F92672",
  storage: "#F92672",
  variable: "#FD971F",
  parameter: "#FD971F",
  function: "#66D9EF",
  string: "#E6DB74",
  constant: "#AE81FF",
  type: "#66D9EF",
  class: "#A6E22E",
  number: "#AE81FF",
  comment: "#88846f",
  heading: "#A6E22E",
  invalid: "#F44747",
  regexp: "#E6DB74",
  tag: "#F92672",
}

export default {
  variant: "dark",
  settings: {
    background: c.background,
    foreground: c.foreground,
    caret: c.cursor,
    selection: c.selection,
    selectionMatch: c.selection,
    gutterBackground: c.background,
    gutterForeground: c.foreground,
    lineHighlight: c.activeLine,
  },
  styles: [
    { tag: "keyword", color: c.keyword },
    { tag: ["name", "deleted", "character", "macroName"], color: c.variable },
    { tag: ["propertyName"], color: c.function },
    {
      tag: ["processingInstruction", "string", "inserted", "special.string"],
      color: c.string,
    },
    { tag: ["function.variableName", "labelName"], color: c.function },
    { tag: ["color", "constant.name", "standard.name"], color: c.constant },
    { tag: ["definition.name", "separator"], color: c.variable },
    { tag: ["className"], color: c.class },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: c.number,
    },
    { tag: ["typeName"], color: c.type, fontStyle: c.type },
    { tag: ["operator", "operatorKeyword"], color: c.keyword },
    { tag: ["url", "escape", "regexp", "link"], color: c.regexp },
    { tag: ["meta", "comment"], color: c.comment },
    { tag: "tagName", color: c.tag },
    { tag: "strong", fontWeight: "bold" },
    { tag: "emphasis", fontStyle: "italic" },
    { tag: "link", textDecoration: "underline" },
    { tag: "heading", fontWeight: "bold", color: c.heading },
    { tag: ["atom", "bool", "special.variableName"], color: c.variable },
    { tag: "invalid", color: c.invalid },
    { tag: "strikethrough", textDecoration: "line-through" },
  ],
}
