const c = {
  background: "#1e1e1e",
  foreground: "#c5c8c6",
  selection: "#4747a1",
  selectionMatch: "#4747a1",
  cursor: "var(--cursor-#c07020)",
  dropdownBackground: "#525252",
  activeLine: "#30303078",
  matchingBracket: "#303030",
  keyword: "#676867",
  storage: "#676867",
  variable: "#c7444a",
  parameter: "#6089B4",
  function: "#9872A2",
  string: "#D08442",
  constant: "#8080FF",
  type: "#9B0000",
  class: "#CE6700",
  number: "#6089B4",
  comment: "#9A9B99",
  heading: "#D0B344",
  invalid: "#FF0B00",
  regexp: "#D08442",
  tag: "#6089B4",
}

export default {
  variant: "dark",
  settings: {
    background: c.background,
    foreground: c.foreground,
    caret: c.cursor,
    selection: c.selection,
    selectionMatch: c.selection,
    gutterBackground: c.background,
    gutterForeground: c.foreground,
    lineHighlight: c.activeLine,
  },
  styles: [
    { tag: "keyword", color: c.keyword },
    { tag: ["name", "deleted", "character", "macroName"], color: c.variable },
    { tag: ["propertyName"], color: c.function },
    {
      tag: ["processingInstruction", "string", "inserted", "special.string"],
      color: c.string,
    },
    { tag: ["function.variableName", "labelName"], color: c.function },
    { tag: ["color", "constant.name", "standard.name"], color: c.constant },
    { tag: ["definition.name", "separator"], color: c.variable },
    { tag: ["className"], color: c.class },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: c.number,
    },
    { tag: ["typeName"], color: c.type, fontStyle: c.type },
    { tag: ["operator", "operatorKeyword"], color: c.keyword },
    { tag: ["url", "escape", "regexp", "link"], color: c.regexp },
    { tag: ["meta", "comment"], color: c.comment },
    { tag: "tagName", color: c.tag },
    { tag: "strong", fontWeight: "bold" },
    { tag: "emphasis", fontStyle: "italic" },
    { tag: "link", textDecoration: "underline" },
    { tag: "heading", fontWeight: "bold", color: c.heading },
    { tag: ["atom", "bool", "special.variableName"], color: c.variable },
    { tag: "invalid", color: c.invalid },
    { tag: "strikethrough", textDecoration: "line-through" },
  ],
}
