export default {
  variant: "light",
  settings: {
    background: "#f2f1f8",
    foreground: "#0c006b",
    caret: "#5c49e9",
    selection: "#d5d1f2",
    selectionMatch: "#d5d1f2",
    gutterBackground: "#f2f1f8",
    gutterForeground: "#0c006b70",
    lineHighlight: "#16067911",
  },
  styles: [
    { tag: "comment", color: "#9995b7" },
    {
      tag: "keyword",
      color: "#ff5792",
      fontWeight: "bold",
    },
    { tag: ["definitionKeyword", "modifier"], color: "#ff5792" },
    { tag: ["className", "tagName", "definition.typeName"], color: "#0094f0" },
    { tag: ["number", "bool", "null", "special.brace"], color: "#5842ff" },
    {
      tag: ["definition.propertyName", "function.variableName"],
      color: "#0095a8",
    },
    { tag: "typeName", color: "#b3694d" },
    { tag: ["propertyName", "variableName"], color: "#fa8900" },
    { tag: "operator", color: "#ff5792" },
    { tag: "self", color: "#e64100" },
    { tag: ["string", "regexp"], color: "#00b368" },
    { tag: ["paren", "bracket"], color: "#0431fa" },
    { tag: "labelName", color: "#00bdd6" },
    { tag: "attributeName", color: "#e64100" },
    { tag: "angleBracket", color: "#9995b7" },
  ],
}
