// Colors from https://www.nordtheme.com/docs/colors-and-palettes

export default {
  variant: "dark",
  settings: {
    background: "#2e3440",
    foreground: "#FFFFFF",
    caret: "#FFFFFF",
    selection: "#00000073",
    selectionMatch: "#00000073",
    gutterBackground: "#2e3440",
    gutterForeground: "#4c566a",
    gutterActiveForeground: "#d8dee9",
    lineHighlight: "#4c566a29",
  },
  styles: [
    { tag: "keyword", color: "#5e81ac" },
    {
      tag: ["name", "deleted", "character", "propertyName", "macroName"],
      color: "#88c0d0",
    },
    { tag: ["variableName"], color: "#8fbcbb" },
    { tag: ["function.variableName"], color: "#8fbcbb" },
    { tag: ["labelName"], color: "#81a1c1" },
    { tag: ["color", "constant.name", "standard.name"], color: "#5e81ac" },
    { tag: ["definition.name", "separator"], color: "#a3be8c" },
    { tag: ["brace"], color: "#8fbcbb" },
    { tag: ["annotation"], color: "#d30102" },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: "#b48ead",
    },
    { tag: ["typeName", "className"], color: "#ebcb8b" },
    { tag: ["operator", "operatorKeyword"], color: "#a3be8c" },
    { tag: ["tagName"], color: "#b48ead" },
    { tag: ["squareBracket"], color: "#bf616a" },
    { tag: ["angleBracket"], color: "#d08770" },
    { tag: ["attributeName"], color: "#ebcb8b" },
    { tag: ["regexp"], color: "#5e81ac" },
    { tag: ["quote"], color: "#b48ead" },
    { tag: ["string"], color: "#a3be8c" },
    {
      tag: "link",
      color: "#a3be8c",
      textDecoration: "underline",
      textUnderlinePosition: "under",
    },
    { tag: ["url", "escape", "special.string"], color: "#8fbcbb" },
    { tag: ["meta"], color: "#88c0d0" },
    { tag: ["monospace"], color: "#d8dee9", fontStyle: "italic" },
    { tag: ["comment"], color: "#4c566a", fontStyle: "italic" },
    { tag: "strong", fontWeight: "bold", color: "#5e81ac" },
    { tag: "emphasis", fontStyle: "italic", color: "#5e81ac" },
    { tag: "strikethrough", textDecoration: "line-through" },
    { tag: "heading", fontWeight: "bold", color: "#5e81ac" },
    { tag: "special.heading1", fontWeight: "bold", color: "#5e81ac" },
    { tag: "heading1", fontWeight: "bold", color: "#5e81ac" },
    {
      tag: ["heading2", "heading3", "heading4"],
      fontWeight: "bold",
      color: "#5e81ac",
    },
    { tag: ["heading5", "heading6"], color: "#5e81ac" },
    { tag: ["atom", "bool", "special.variableName"], color: "#d08770" },
    { tag: ["processingInstruction", "inserted"], color: "#8fbcbb" },
    { tag: ["contentSeparator"], color: "#ebcb8b" },
    { tag: "invalid", color: "#434c5e", borderBottom: `1px dotted #d30102` },
  ],
}
