const c = {
  background: "#F5F5F5",
  foreground: "#333333",
  selection: "#C9D0D9",
  selectionMatch: "#C9D0D9",
  cursor: "var(--cursor-#54494B)",
  dropdownBackground: "#F5F5F5",
  activeLine: "#79ff002b",
  matchingBracket: "#E4F6D4",
  keyword: "#4B69C6",
  storage: "#4B69C6",
  variable: "#7A3E9D",
  parameter: "#7A3E9D",
  function: "#AA3731",
  string: "#448C27",
  constant: "#9C5D27",
  type: "#7A3E9D",
  class: "#AA3731",
  number: "#9C5D27",
  comment: "#AAAAAA",
  heading: "#AA3731",
  invalid: "#cd3131",
  regexp: "#4B69C6",
  tag: "#4B69C6",
}

export default {
  variant: "light",
  settings: {
    background: c.background,
    foreground: c.foreground,
    caret: c.cursor,
    selection: c.selection,
    selectionMatch: c.selection,
    gutterBackground: c.background,
    gutterForeground: c.foreground,
    gutterBorder: "transparent",
    lineHighlight: c.activeLine,
  },
  styles: [
    { tag: "keyword", color: c.keyword },
    { tag: ["name", "deleted", "character", "macroName"], color: c.variable },
    { tag: ["propertyName"], color: c.function },
    {
      tag: ["processingInstruction", "string", "inserted", "special.string"],
      color: c.string,
    },
    { tag: ["function.variableName", "labelName"], color: c.function },
    { tag: ["color", "constant.name", "standard.name"], color: c.constant },
    { tag: ["definition.name", "separator"], color: c.variable },
    { tag: ["className"], color: c.class },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: c.number,
    },
    { tag: ["typeName"], color: c.type, fontStyle: c.type },
    { tag: ["operator", "operatorKeyword"], color: c.keyword },
    { tag: ["url", "escape", "regexp", "link"], color: c.regexp },
    { tag: ["meta", "comment"], color: c.comment },
    { tag: "tagName", color: c.tag },
    { tag: "strong", fontWeight: "bold" },
    { tag: "emphasis", fontStyle: "italic" },
    { tag: "link", textDecoration: "underline" },
    { tag: "heading", fontWeight: "bold", color: c.heading },
    { tag: ["atom", "bool", "special.variableName"], color: c.variable },
    { tag: "invalid", color: c.invalid },
    { tag: "strikethrough", textDecoration: "line-through" },
  ],
}
