const c = {
  background: "#390000",
  foreground: "#F8F8F8",
  selection: "#750000",
  selectionMatch: "#750000",
  cursor: "var(--cursor-#970000)",
  dropdownBackground: "#580000",
  activeLine: "#ff000033",
  matchingBracket: "#ff000033",
  keyword: "#f12727ff",
  storage: "#ff6262ff",
  variable: "#edef7dff",
  parameter: "#edef7dff",
  function: "#ffb454ff",
  string: "#edef7dff",
  constant: "#ec0d1e",
  type: "#9df39fff",
  class: "#fec758ff",
  number: "#994646ff",
  comment: "#e7c0c0ff",
  heading: "#fec758ff",
  invalid: "#ffffffff",
  regexp: "#edef7dff",
  tag: "#aa5507ff",
}

export default {
  variant: "dark",
  settings: {
    background: c.background,
    foreground: c.foreground,
    caret: c.cursor,
    selection: c.selection,
    selectionMatch: c.selection,
    gutterBackground: c.background,
    gutterForeground: c.foreground,
    lineHighlight: c.activeLine,
  },
  styles: [
    { tag: "keyword", color: c.keyword },
    { tag: ["name", "deleted", "character", "macroName"], color: c.variable },
    { tag: ["propertyName"], color: c.function },
    {
      tag: ["processingInstruction", "string", "inserted", "special.string"],
      color: c.string,
    },
    { tag: ["function.variableName", "labelName"], color: c.function },
    { tag: ["color", "constant.name", "standard.name"], color: c.constant },
    { tag: ["definition.name", "separator"], color: c.variable },
    { tag: ["className"], color: c.class },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: c.number,
    },
    { tag: ["typeName"], color: c.type, fontStyle: c.type },
    { tag: ["operator", "operatorKeyword"], color: c.keyword },
    { tag: ["url", "escape", "regexp", "link"], color: c.regexp },
    { tag: ["meta", "comment"], color: c.comment },
    { tag: "tagName", color: c.tag },
    { tag: "strong", fontWeight: "bold" },
    { tag: "emphasis", fontStyle: "italic" },
    { tag: "link", textDecoration: "underline" },
    { tag: "heading", fontWeight: "bold", color: c.heading },
    { tag: ["atom", "bool", "special.variableName"], color: c.variable },
    { tag: "invalid", color: c.invalid },
    { tag: "strikethrough", textDecoration: "line-through" },
  ],
}
