const c = {
  background: "#002B36",
  foreground: "#839496",
  selection: "#004454AA",
  selectionMatch: "#005A6FAA",
  cursor: "var(--cursor-#D30102)",
  dropdownBackground: "#00212B",
  dropdownBorder: "#2AA19899",
  activeLine: "#00cafe11",
  matchingBracket: "#073642",
  keyword: "#859900",
  storage: "#93A1A1",
  variable: "#268BD2",
  parameter: "#268BD2",
  function: "#268BD2",
  string: "#2AA198",
  constant: "#CB4B16",
  type: "#859900",
  class: "#268BD2",
  number: "#D33682",
  comment: "#586E75",
  heading: "#268BD2",
  invalid: "#DC322F",
  regexp: "#DC322F",
  tag: "#268BD2",
}

export default {
  variant: "dark",
  settings: {
    background: c.background,
    foreground: c.foreground,
    caret: c.cursor,
    selection: c.selection,
    selectionMatch: c.selection,
    gutterBackground: c.background,
    gutterForeground: c.foreground,
    gutterBorder: "transparent",
    lineHighlight: c.activeLine,
  },
  styles: [
    { tag: "keyword", color: c.keyword },
    { tag: ["name", "deleted", "character", "macroName"], color: c.variable },
    { tag: ["propertyName"], color: c.function },
    {
      tag: ["processingInstruction", "string", "inserted", "special.string"],
      color: c.string,
    },
    { tag: ["function.variableName", "labelName"], color: c.function },
    { tag: ["color", "constant.name", "standard.name"], color: c.constant },
    { tag: ["definition.name", "separator"], color: c.variable },
    { tag: ["className"], color: c.class },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: c.number,
    },
    { tag: ["typeName"], color: c.type, fontStyle: c.type },
    { tag: ["operator", "operatorKeyword"], color: c.keyword },
    { tag: ["url", "escape", "regexp", "link"], color: c.regexp },
    { tag: ["meta", "comment"], color: c.comment },
    { tag: "tagName", color: c.tag },
    { tag: "strong", fontWeight: "bold" },
    { tag: "emphasis", fontStyle: "italic" },
    { tag: "link", textDecoration: "underline" },
    { tag: "heading", fontWeight: "bold", color: c.heading },
    { tag: ["atom", "bool", "special.variableName"], color: c.variable },
    { tag: "invalid", color: c.invalid },
    { tag: "strikethrough", textDecoration: "line-through" },
  ],
}
