export default {
  variant: "dark",
  settings: {
    background: "#1a1b26",
    foreground: "#787c99",
    caret: "#c0caf5",
    selection: "#515c7e40",
    selectionMatch: "#16161e",
    gutterBackground: "#1a1b26",
    gutterForeground: "#787c99",
    gutterBorder: "transparent",
    lineHighlight: "#474b6611",
  },
  styles: [
    { tag: "keyword", color: "#bb9af7" },
    { tag: ["name", "deleted", "character", "macroName"], color: "#c0caf5" },
    { tag: ["propertyName"], color: "#7aa2f7" },
    {
      tag: ["processingInstruction", "string", "inserted", "special.string"],
      color: "#9ece6a",
    },
    { tag: ["function.variableName", "labelName"], color: "#7aa2f7" },
    { tag: ["color", "constant.name", "standard.name"], color: "#bb9af7" },
    { tag: ["definition.name", "separator"], color: "#c0caf5" },
    { tag: ["className"], color: "#c0caf5" },
    {
      tag: ["number", "changed", "annotation", "modifier", "self", "namespace"],
      color: "#ff9e64",
    },
    { tag: ["typeName"], color: "#0db9d7" },
    { tag: ["operator", "operatorKeyword"], color: "#bb9af7" },
    { tag: ["url", "escape", "regexp", "link"], color: "#b4f9f8" },
    { tag: ["meta", "comment"], color: "#444b6a" },
    { tag: "strong", fontWeight: "bold" },
    { tag: "emphasis", fontStyle: "italic" },
    { tag: "link", textDecoration: "underline" },
    { tag: "heading", fontWeight: "bold", color: "#89ddff" },
    { tag: ["atom", "bool", "special.variableName"], color: "#c0caf5" },
    { tag: "invalid", color: "#ff5370" },
    { tag: "strikethrough", textDecoration: "line-through" },
  ],
}
