const c = {
  background: "#000",
  foreground: "#fff",
  selection: "#7d46fc3f",
  selectionMatch: "#7d46fc7f",
  cursor: "var(--cursor-#7d46fc)",
  dropdownBackground: "#0a0b0f",
  dropdownBorder: "#1e1d27",
  activeLine: "#00346eb0",
  matchingBracket: "#7d46fc7f",
  keyword: null,
  storage: null,
  variable: null,
  parameter: null,
  function: null,
  string: "#a8a8b1",
  constant: null,
  type: null,
  class: null,
  number: null,
  comment: "#2e2e37",
  heading: null,
  invalid: null,
  regexp: "#a8a8b1",
  tag: null,
}

export default {
  variant: "dark",
  settings: {
    background: c.background,
    foreground: c.foreground,
    caret: c.cursor,
    selection: c.selection,
    selectionMatch: c.selectionMatch,
    gutterBackground: c.background,
    gutterForeground: c.foreground,
    lineHighlight: c.activeLine,
  },
  styles: [
    { tag: "keyword", color: c.keyword, fontWeight: "bold" },
    { tag: ["name", "deleted", "character", "macroName"], color: c.variable },
    { tag: ["propertyName"], color: c.function },
    {
      tag: ["processingInstruction", "string", "inserted", "special.string"],
      color: c.string,
    },
    { tag: ["function.variableName", "labelName"], color: c.function },
    { tag: ["color", "constant.name", "standard.name"], color: c.constant },
    { tag: ["definition.name", "separator"], color: c.variable },
    { tag: ["className"], color: c.class },
    { tag: ["typeName"], color: c.type, fontStyle: c.type },
    { tag: ["url", "escape", "regexp", "link"], color: c.regexp },
    { tag: ["meta", "comment"], color: c.comment },
    { tag: "tagName", color: c.tag },
    { tag: "strong", fontWeight: "bold" },
    { tag: "emphasis", fontStyle: "italic" },
    { tag: "link", textDecoration: "underline" },
    { tag: "heading", fontWeight: "bold", color: c.heading },
    { tag: ["atom", "special.variableName"], color: c.variable },
    { tag: "invalid", color: c.invalid },
    { tag: "strikethrough", textDecoration: "line-through" },
    {
      tag: ["operatorKeyword", "bool", "null", "variableName"],
      color: c.constant,
    },
    { tag: ["operator"], color: "#bb9af7" },
    { tag: ["number"], color: "#a8a8b1" },
    { tag: ["bracket"], color: "#bb9af7" },
  ],
}
