const c = {
  background: "#fff",
  foreground: "#000",
  selection: "#0064ff26",
  selectionMatch: "#0064ff4c",
  cursor: "var(--cursor-#004bff)",
  dropdownBackground: "#f4f6fc",
  dropdownBorder: "#e7ecf2",
  activeLine: "#0064ff0c",
  matchingBracket: "#0064ff4c",
  keyword: null,
  storage: null,
  variable: null,
  parameter: null,
  function: null,
  string: "#6b7a88",
  constant: null,
  type: null,
  class: null,
  number: null,
  comment: "#bec9d3",
  heading: null,
  invalid: null,
  regexp: "#6b7a88",
  tag: null,
}

export default {
  variant: "light",
  settings: {
    background: c.background,
    foreground: c.foreground,
    caret: c.cursor,
    selection: c.selection,
    selectionMatch: c.selectionMatch,
    gutterBackground: c.background,
    gutterForeground: c.foreground,
    lineHighlight: c.activeLine,
  },
  styles: [
    { tag: "keyword", color: c.keyword, fontWeight: "bold" },
    { tag: ["name", "deleted", "character", "macroName"], color: c.variable },
    { tag: ["propertyName"], color: c.function },
    {
      tag: ["processingInstruction", "string", "inserted", "special.string"],
      color: c.string,
    },
    { tag: ["function.variableName", "labelName"], color: c.function },
    { tag: ["color", "constant.name", "standard.name"], color: c.constant },
    { tag: ["definition.name", "separator"], color: c.variable },
    { tag: ["className"], color: c.class },
    { tag: ["typeName"], color: c.type, fontStyle: c.type },
    { tag: ["url", "escape", "regexp", "link"], color: c.regexp },
    { tag: ["meta", "comment"], color: c.comment },
    { tag: "tagName", color: c.tag },
    { tag: "strong", fontWeight: "bold" },
    { tag: "emphasis", fontStyle: "italic" },
    { tag: "link", textDecoration: "underline" },
    { tag: "heading", fontWeight: "bold", color: c.heading },
    { tag: ["atom", "special.variableName"], color: c.variable },
    { tag: "invalid", color: c.invalid },
    { tag: "strikethrough", textDecoration: "line-through" },
    {
      tag: ["operatorKeyword", "bool", "null", "variableName"],
      color: c.constant,
    },
    { tag: ["operator"], color: "#0431fa" },
    { tag: ["number"], color: "#a8a8b1" },
    { tag: ["bracket"], color: "#0431fa" },
  ],
}
