;Copyright © Gil Brasileiro Fernandes. 1997

[CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=%ThemeDir%Green Day\Green Day - Meu Computador.ico,0

[CLSID\{208D2C60-3AEA-1069-A2D7-08002B30309D}\DefaultIcon]
DefaultValue=%ThemeDir%Green Day\Green Day - Ambiente de Rede.ico,0

[CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
full=%ThemeDir%Green Day\Green Day - Lixeira Cheia.ico,0
empty=%ThemeDir%Green Day\Green Day - Lixeira Vazia.ico,0

[Control Panel\Cursors]
Arrow=%ThemeDir%Green Day\Green Day - seta.cur
Help=%ThemeDir%Green Day\Green Day - ajuda.cur
AppStarting=%ThemeDir%Green Day\Green Day - aguardando.ani
Wait=%ThemeDir%Green Day\Green Day - ocupado.ani
NWPen=%ThemeDir%Green Day\Green Day - caneta.cur
No=%ThemeDir%Green Day\Green Day - proibido.cur
SizeNS=%ThemeDir%Green Day\Green Day - N-S.cur
SizeWE=%ThemeDir%Green Day\Green Day - O-L.cur
Crosshair=%ThemeDir%Green Day\Green Day - cruz.cur
IBeam=%ThemeDir%Green Day\Green Day - Marcador.cur
SizeNWSE=%ThemeDir%Green Day\Green Day - NO-SE.cur
SizeNESW=%ThemeDir%Green Day\Green Day - NE-SO.cur
SizeAll=%ThemeDir%Green Day\Green Day - direções.cur
UpArrow=%ThemeDir%Green Day\Green Day - acima.cur
DefaultValue=

[Control Panel\Desktop]
Wallpaper=%ThemeDir%GREEN DAY\GREEN DAY - WALLPAPER.JPG
Pattern=(None)
TileWallpaper=0
WallpaperStyle=0

[AppEvents\Schemes\Apps\.Default\.Default\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\AppGPFault\.Current]
DefaultValue=%ThemeDir%Green Day\Green Day - gdshit.wav

[AppEvents\Schemes\Apps\.Default\Maximize\.Current]
DefaultValue=%ThemeDir%Green Day\Green Day - gdguitar.wav

[AppEvents\Schemes\Apps\.Default\MenuCommand\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\MenuPopup\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\Minimize\.Current]
DefaultValue=%ThemeDir%Green Day\Green Day - gdguitar2.wav

[AppEvents\Schemes\Apps\.Default\Open\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\Close\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\RestoreDown\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\RestoreUp\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\RingIn\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\Ringout\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\SystemAsterisk\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\SystemDefault\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\SystemExclamation\.Current]
DefaultValue=%ThemeDir%Green Day\Green Day - gddookie.wav

[AppEvents\Schemes\Apps\.Default\SystemExit\.Current]
DefaultValue=%ThemeDir%Green Day\Green Day - gdbye.wav

[AppEvents\Schemes\Apps\.Default\SystemHand\.Current]
DefaultValue=%ThemeDir%Green Day\Green Day - gdidiot.wav

[AppEvents\Schemes\Apps\.Default\SystemQuestion\.Current]
DefaultValue=

[AppEvents\Schemes\Apps\.Default\SystemStart\.Current]
DefaultValue=%ThemeDir%Green Day\Green Day - gdintro.wav

[AppEvents\Schemes\Apps\Explorer\EmptyRecycleBin\.Current]
DefaultValue=

[Metrics]
IconMetrics=76 0 0 0 75 0 0 0 75 0 0 0 1 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 0 0 0 0 0 76 117 99 105 100 97 32 83 97 110 115 32 85 110 105 99 111 100 101 0 116 114 111 46 119 97 118 0 0 0 0 0
NonclientMetrics=84 1 0 0 1 0 0 0 13 0 0 0 13 0 0 0 18 0 0 0 18 0 0 0 243 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 188 2 0 0 0 0 0 0 0 0 0 0 65 114 105 97 108 0 108 117 115 33 92 84 104 101 109 101 115 92 71 114 101 101 110 32 68 97 121 46 84 104 101 109 16 0 0 0 16 0 0 0 247 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 188 2 0 0 0 0 0 0 0 0 0 0 76 117 99 105 100 97 32 83 97 110 115 32 85 110 105 99 111 100 101 0 101 101 110 32 68 97 121 46 84 104 101 109 18 0 0 0 18 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 0 0 0 0 0 76 117 99 105 100 97 32 83 97 110 115 32 85 110 105 99 111 100 101 0 101 101 110 32 68 97 121 46 84 104 101 109 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 0 0 0 0 0 76 117 99 105 100 97 32 83 97 110 115 32 85 110 105 99 111 100 101 0 101 101 110 32 68 97 121 46 84 104 101 109 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 0 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 105 99 111 100 101 0 101 101 110 32 68 97 121 46 84 104 101 109

[Control Panel\Colors]
ActiveTitle=24 56 24
Background=19 45 24
Hilight=16 56 16
HilightText=144 224 144
TitleText=0 255 128
Window=255 255 255
WindowText=0 0 0
Scrollbar=192 224 224
InactiveTitle=72 144 144
Menu=128 192 192
WindowFrame=0 0 0
MenuText=0 0 0
ActiveBorder=126 192 192
InactiveBorder=126 192 192
AppWorkspace=69 141 141
ButtonFace=128 192 192
ButtonShadow=72 144 144
GrayText=72 144 144
ButtonText=0 0 0
InactiveTitleText=168 200 168
ButtonHilight=192 224 224
ButtonDkShadow=0 0 0
ButtonLight=128 192 192
InfoText=128 224 128
InfoWindow=24 56 24

[boot]
SCRNSAVE.EXE=%WinDir%SYSTEM\GREEND~1.SCR

[MasterThemeSelector]
MTSM=DABJDKT
