export const GM_INSTRUMENTS = [
  "Piano         ",
  "Bright Piano  ",
  "Electric Piano",
  "Honky-tonk    ",
  "Rhodes Piano  ",
  "FM Piano      ",
  "Harpsichord   ",
  "Clavinet      ",
  "Celesta       ",
  "Glockenspiel  ",
  "Music Box     ",
  "Vibraphone    ",
  "Marimba       ",
  "Xylophone     ",
  "Tubular Bells ",
  "Dulcimer      ",
  "Drawbar Organ ",
  "Perc Organ    ",
  "Rock Organ    ",
  "Church Organ  ",
  "Reed Organ    ",
  "Accordion     ",
  "Harmonica     ",
  "Accordion     ",
  "Steel Guitar  ",
  "Nylon Guitar  ",
  "Jazz Guitar   ",
  "Clean Guitar  ",
  "Muted Guitar  ",
  "Overdrive Guit",
  "Distort Guitar",
  "Guit Harmonics",
  "Acoustic Bass ",
  "Finger Bass   ",
  "Picked Bass   ",
  "Fretless Bass ",
  "Slap Bass 1   ",
  "Slap Bass 2   ",
  "Synth Bass 1  ",
  "Synth Bass 2  ",
  "Violin        ",
  "Viola         ",
  "Cello         ",
  "Contrabass    ",
  "Trem Strings  ",
  "Pizz Strings  ",
  "Harp          ",
  "Timpani       ",
  "String Ens 1  ",
  "String Ens 2  ",
  "Syn Strings 1 ",
  "Syn Strings 2 ",
  "Choir Aahs    ",
  "Voice Oohs    ",
  "Synth Voice   ",
  "Orch Hit      ",
  "Trumpet       ",
  "Trombone      ",
  "Tuba          ",
  "Muted Trumpet ",
  "French Horn   ",
  "Brass Section ",
  "SynthBrass 1  ",
  "SynthBrass 2  ",
  "Soprano Sax   ",
  "Alto Sax      ",
  "Tenor Sax     ",
  "Baritone Sax  ",
  "Oboe          ",
  "English Horn  ",
  "Bassoon       ",
  "Clarinet      ",
  "Piccolo       ",
  "Flute         ",
  "Recorder      ",
  "Pan Flute     ",
  "Blown Bottle  ",
  "Shakuhachi    ",
  "Whistle       ",
  "Ocarina       ",
  "Lead: Square  ",
  "Lead: Sawtooth",
  "Lead: Calliope",
  "Lead: Chiff   ",
  "Lead: Charang ",
  "Lead: Voice   ",
  "Lead: Fifths  ",
  "Lead: Bass    ",
  "Pad: New Age  ",
  "Pad: Warm     ",
  "Pad: Polysynth",
  "Pad: Choir    ",
  "Pad: Bowed    ",
  "Pad: Metallic ",
  "Pad: Halo     ",
  "Pad: Sweep    ",
  "FX: Rain      ",
  "FX: Soundtrack",
  "FX: Crystal   ",
  "FX: Atmosphere",
  "FX: Brightness",
  "FX: Goblins   ",
  "FX: Echoes    ",
  "FX: Sci-fi    ",
  "Sitar         ",
  "Banjo         ",
  "Shamisen      ",
  "Koto          ",
  "Kalimba       ",
  "Bag pipe      ",
  "Fiddle        ",
  "Shanai        ",
  "Tinkle Bell   ",
  "Agogo         ",
  "Steel Drums   ",
  "Woodblock     ",
  "Taiko Drum    ",
  "Melodic Tom   ",
  "Synth Drum    ",
  "Reverse Cym   ",
  "Fret Noise    ",
  "Breath Noise  ",
  "Seashore      ",
  "Bird Tweet    ",
  "Telephone Ring",
  "Helicopter    ",
  "Applause      ",
  "Gunshot       ",
]

export const GM_DRUM_KITS = {
  0: "Std Drumkit   ",
  8: "Room Drumkit  ",
  16: "Power Drumkit ",
  24: "Elec Drumkit  ",
  25: "TR808 Drumkit ",
  32: "Jazz Drumkit  ",
  40: "Brush Drumkit ",
}

export const SOUNDFONTS = [
  {
    label: "User SoundFonts (Drop .sf2 to add)",
    items: [],
  },
  {
    label: "Small Soundfonts",
    items: [
      { label: "Roland SC-55/SCC1 (3.3 MB)", value: "Scc1t2.sf2" },
      { label: "GMGSx Plus (6.2 MB)", value: "gmgsx-plus.sf2" },
      { label: "Yamaha DB50XG (3.9 MB)", value: "Yamaha DB50XG.sf2" },
      {
        label: "Gravis Ultrasound (5.9 MB)",
        value: "Gravis_Ultrasound_Classic_PachSet_v1.6.sf2",
      },
      { label: "Tim GM (6 MB)", value: "TimGM6mb.sf2" },
      { label: "Alan Chan 5MBGMGS (4.9 MB)", value: "5MBGMGS.SF2" },
      { label: "E-mu 2MBGMGS (2.1 MB)", value: "2MBGMGS.SF2" },
      { label: "E-mu 8MBGMGS (8.2 MB)", value: "8MBGMGS.SF2" },
      { label: "Phoenix MT-32 (6.3 MB)", value: "Phoenix_MT-32.sf2" },
    ],
  },
  {
    label: "Large Soundfonts",
    items: [
      { label: "Masquerade 55 v006 (18.4 MB)", value: "masquerade55v006.sf2" },
      { label: "GeneralUser GS v1.471 (31.3 MB)", value: "generaluser.sf2" },
      { label: "GeneralUser GS v2.0.1 (32.3 MB)", value: "generaluser2.sf2" },
      { label: "Chorium Revision A (28.9 MB)", value: "choriumreva.sf2" },
      { label: "Unison (29.3 MB)", value: "Unison.SF2" },
      { label: "Creative 28MBGM (29.7 MB)", value: "28MBGM.sf2" },
      { label: "Musica Theoria 2 (30.5 MB)", value: "mustheory2.sf2" },
      { label: "Personal Copy Lite (31.4 MB)", value: "PCLite.sf2" },
      { label: "AnotherXG (31.4 MB)", value: "bennetng_AnotherXG_v2-1.sf2" },
      { label: "NTONYX 32Mb GM Stereo (32.5 MB)", value: "32MbGMStereo.sf2" },
      { label: "Weeds GM 3 (54.9 MB)", value: "weedsgm3.sf2" },
      { label: "Weeds GM 4 (68.5 MB)", value: "WeedsGM4.sf2" },
      { label: "EmperorGrieferus SC-55 (58.7 MB)", value: "SC-55.sf2" },
      // https://www.youtube.com/watch?v=_J8-CgvC-As
      // https://drive.google.com/open?id=1G53wKnIBMONgOVx0gCOWrBlJaXsyaKml
    ],
  },
  {
    label: "Novelty Soundfonts",
    items: [
      { label: "PC Beep (31 KB)", value: "pcbeep.sf2" },
      { label: "Nokia 6230i (227 KB)", value: "Nokia_6230i_RM-72_.sf2" },
      {
        label: "Kirby's Dream Land (271 KB)",
        value: "Kirby's_Dream_Land_3.sf2",
      },
      {
        label: "Vintage Waves v2 (315 KB)",
        value: "Vintage Dreams Waves v2.sf2",
      },
      {
        label: "Setzer's SPC Soundfont (1.2 MB)",
        value: "Setzer's_SPC_Soundfont.sf2",
      },
      {
        label: "SNES GM (1.9 MB)",
        value: "Super_Nintendo_Unofficial_update.sf2",
      },
      { label: "Nokia 30 (2.2 MB)", value: "Nokia_30.sf2" },
      {
        label: "LG Wink/Motorola ROKR (3.3 MB)",
        value: "LG_Wink_Style_T310_Soundfont.sf2",
      },
      {
        label: "Diddy Kong Racing DS (13.7 MB)",
        value: "Diddy_Kong_Racing_DS_Soundfont.sf2",
      },
      {
        label: "Regression FM v1.99g (14.4 MB)",
        value: "R_FM_v1.99g-beta.sf2",
      },
      {
        label: "Ultimate Megadrive (63.2 MB)",
        value: "The Ultimate Megadrive Soundfont.sf2",
      },
    ],
  },
  {
    label: "Piano Soundfonts",
    items: [
      {
        label: "Yamaha Grand Lite v1.1 (21.8 MB)",
        value: "Yamaha-Grand-Lite-v1.1.sf2",
      },
      {
        label: "Abbey Steinway D v1.9 (40.2 MB)",
        value: "Abbey-Steinway-D-v1.9.sf2",
      },
      {
        label: "Chateau Grand Lite v1.0 (49.1 MB)",
        value: "Chateau Grand Lite-v1.0.sf2",
      },
      {
        label: "Steinway Grand v1.0 (145 MB)",
        value: "Steinway Grand-SF4U-v1.sf2",
      },
    ],
  },
]
